name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your main branch if different
  pull_request:
    branches:
      - main  # Change to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install  # or yarn install if using Yarn

      - name: Run tests
        run: npm test  # or yarn test if using Yarn

      - name: Build
        run: npm run build  # or your build command
